#!/usr/bin/env python3
"""Write `reconstruct/nopad/game.h`: the header with the padding taken out.

A `_pad_*` field is a claim that nothing reads those bytes, and every check in
this repository tests that claim from the outside - pad_writes.py watches for
writes, gen_data.py reports which pointers land in one. This tests it from the
inside: take the fields **out**, let every named field slide up against its
neighbour, and see whether the game still plays.

It works at all only because `data.c` computes the game's own pointers from
the fields they name - `GOFF(backdrop[2])`, not 0x6f1f. Move a field and every
pointer to it moves with it, so the whole image stays self-consistent under a
layout the original never had. Anything that breaks is a byte the port reads
without having named it, which is exactly the thing that cannot be found by
reading code.

The header is **generated**, not a copy, so it cannot drift from the one it
came from: the transform is three rules -

  * drop every `ENSURE_…(…)` line, since none of the offsets hold any more;
  * drop every field whose name begins with `_`;
  * re-derive the four segment overlays and IMAGE_LEN from `image_t`, which
    is now a different size.

    uv run gen_nopad.py            # -> reconstruct/nopad/game.h
    cd reconstruct && make nopad   # -> popcorn-nopad

`--unpacked` is the same machinery put to a different use: it keeps every
field and takes out `__attribute__((packed))` instead, so each word lands on
an even address. That is the Amiga build's header. A 68000 raises an address
error on a word read from an odd address, and the image as it shipped has
most of its words at odd offsets; unpacked, the compiler pads them into line,
and data.c's computed pointers follow the fields exactly as they do here.
Every segment still fits in 16 bits - the largest is assets_t at 0x85ae.

That header is **committed**, under reconstruct/amiga/, because the split
repository has Makefile.amiga and not this script. `--check` says whether it
is current.

    uv run gen_nopad.py --unpacked            # -> reconstruct/amiga/game_unpacked.h
    uv run gen_nopad.py --unpacked --check
"""
import argparse
import hashlib
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "reconstruct", "src", "game.h")
OUT = os.path.join(HERE, "reconstruct", "nopad", "game.h")
OUT_UNPACKED = os.path.join(HERE, "reconstruct", "amiga", "game_unpacked.h")
PACKED = "__attribute__((packed))"

# A member declaration whose name starts with an underscore: `uint8_t
# _pad_00[74];`, `uint8_t _r[4];`, `assets_t _gap[2];`. Anchored on the
# leading whitespace so a `#define _x` or a comment cannot match.
FIELD = re.compile(r"^\s+[A-Za-z_][\w]*\s+(_\w+)\s*(?:\[[^\]]*\]\s*)*;")
ENSURE = re.compile(r"^ENSURE_\w+\(")
# One assertion is written out longhand rather than through a macro, and it
# spans several lines: the head node's `next` landing on 0x3144. It is exactly
# the kind of thing that stops holding here, so it goes too.
LONGHAND = re.compile(r"^typedef char ensure_")

# The three segment bases, rewritten **where they are defined** rather than in
# the tail. game.h defines global_ptr, runtime_ptr and the rest as static
# inline functions right after each overlay, so a macro fixed at the end of
# the header comes far too late for them - they would keep the original
# literals and read a segment that has moved. The values cannot be written as
# sizeof() sums either, because a kept gap belongs between two segments; so
# they become extern constants and data.c computes them with offsetof.
SEG_DEFS = [
    ("#define SEG_ASSETS 0xc460", "SEG_ASSETS", "popcorn_seg_assets"),
    ("#define SEG_ANIMATIONS 0x14a10", "SEG_ANIMATIONS", "popcorn_seg_animations"),
    ("#define SEG_RUNTIME 0x1ac20", "SEG_RUNTIME", "popcorn_seg_runtime"),
]

TAIL = """
/* ---------------------------------------------------------------------
 * Generated by ../../gen_nopad.py. Everything above is game.h with the
 * assertions and the `_`-named fields removed; what follows re-derives what
 * those removals invalidated.
 *
 * The segment bases are handled where they are defined, not here - see
 * SEG_DEFS in gen_nopad.py, and the note there about the header's inline
 * accessors. All that is left for the tail is the image's length.
 * ------------------------------------------------------------------ */
/* The four overlay macros stay exactly as game.h wrote them: they are built
 * from SEG_ASSETS and friends, which are now correct where they are defined,
 * so every inline accessor in the header picks up the right base. Only the
 * image's length has to wait for image_t. */
#undef IMAGE_LEN
#define IMAGE_LEN ((int32_t)sizeof(image_t))
"""


def stamp(text):
    """What Makefile.amiga compares: the first sixteen hex digits of
    game.h's SHA-256. The unpacked header arrives through -include and
    game.h's guard then makes the real one expand to nothing, so a stale
    copy would be built from without a word - this is the word."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def transform(text, keep=(), unpacked=False):
    out, dropped_fields, dropped_asserts = [], 0, 0
    skipping = False
    for line in text.split("\n"):
        if skipping:
            skipping = not line.rstrip().endswith(";")
            continue
        if LONGHAND.match(line):
            dropped_asserts += 1
            skipping = not line.rstrip().endswith(";")
            continue
        if ENSURE.match(line):
            dropped_asserts += 1
            continue
        m = FIELD.match(line)
        if m:
            if m.group(1) in keep:      # put this one back for the bisection
                out.append(line)
                continue
            dropped_fields += 1
            continue
        out.append(line)
    body = "\n".join(out)
    if unpacked:
        assert body.count(PACKED) > 0
        body = body.replace(" " + PACKED, "")
        assert PACKED not in body

    for old, name, sym in SEG_DEFS:
        assert body.count(old) == 1, old
        body = body.replace(
            old,
            f"/* {name} is a constant data.c computes from image_t: the header's\n"
            f" * own inline accessors expand it, so it has to be right here and not\n"
            f" * patched up at the end of the file. */\n"
            f"extern const int32_t {sym};\n"
            f"#define {name} {sym}")

    # The tail has to land before the include guard closes.
    end = body.rindex("#endif")
    body = body[:end] + TAIL + "\n" + body[end:]

    if unpacked:
        head = ('/*\n'
                ' * game.h without `packed` - **generated by '
                '../../gen_nopad.py --unpacked.**\n'
                ' *\n'
                ' * Do not edit: edit src/game.h and regenerate. Every field is\n'
                ' * kept and every word is on an even address, which is what a\n'
                ' * 68000 needs. Makefile.amiga builds with it; amiga/seg_bases.c\n'
                ' * defines the three segment bases it declares.\n'
                ' *\n'
                f' * from src/game.h sha256 {stamp(text)}\n'
                ' */\n')
    else:
        head = ('/*\n'
                ' * game.h with the padding taken out - **generated by '
                '../../gen_nopad.py.**\n'
                ' *\n'
                ' * Do not edit: edit src/game.h and regenerate. This exists to be\n'
                ' * compiled and played, not read - see gen_nopad.py for what the\n'
                ' * test is and why it can work at all.\n'
                ' */\n')
    return head + body, dropped_fields, dropped_asserts


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=None)
    ap.add_argument("--unpacked", action="store_true",
                    help="keep every field and drop `packed` instead: the "
                         "Amiga build's header, reconstruct/amiga/"
                         "game_unpacked.h")
    ap.add_argument("--check", action="store_true",
                    help="regenerate and diff without writing")
    ap.add_argument("--keep", default="",
                    help="comma-separated `_`-named fields to put back, for "
                         "finding which one a symptom belongs to. gen_data.py "
                         "takes the same list and both must be given it, or "
                         "the header and the data disagree")
    args = ap.parse_args()

    keep = {x.strip() for x in args.keep.split(",") if x.strip()}
    out = args.out or (OUT_UNPACKED if args.unpacked else OUT)
    src = open(SRC, encoding="utf-8").read()
    if args.unpacked:
        if keep:
            raise SystemExit("gen_nopad: --unpacked keeps every field already")
        keep = {m.group(1) for m in map(FIELD.match, src.split("\n")) if m}
    text, fields, asserts = transform(src, keep, args.unpacked)
    if args.check:
        have = (open(out, encoding="utf-8").read()
                if os.path.exists(out) else None)
        if have == text:
            print(f"{os.path.relpath(out, HERE)} is up to date")
            return 0
        print(f"{os.path.relpath(out, HERE)} is stale", file=sys.stderr)
        return 1
    args.out = out
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    open(args.out, "w", encoding="utf-8").write(text)
    print(f"{os.path.relpath(args.out, HERE)}: {fields} fields and "
          f"{asserts} assertions removed, {len(text):,} bytes"
          + (f"; kept {', '.join(sorted(keep))}"
             if keep and not args.unpacked else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
